hh
name: MyUnideals CI/CD[AWS]

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]


jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build
  

  deployToStaging:
    needs: [buildAndTest]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build
      - run: zip -r ebsdeploy.zip ./dist ./package.json ./Dockerfile ./package-lock.json -x "*.git*" "**node_modules**"
    
      - name: Get timestamp
        id: timestamp
        run: echo "date=$(date +'%Y-%m-%dT%H-%M-%S-%3NZ')" >>$GITHUB_OUTPUT

      - name: Deploying to Staging Environment
        uses: einaregilsson/beanstalk-deploy@v21
        with:
         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
         application_name: staging-server
         environment_name: Stagingserver-env
      
         version_label: "${{ steps.timestamp.outputs.date }}"
         region: "us-east-1"
         deployment_package: ebsdeploy.zip
         existing_bucket_name: elasticbeanstalk-us-east-1-940580490955
